name: Deployment workflow

on:
  push:
    branches: [main]

env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
  TEST_MONGODB_URI: ${{ secrets.TEST_MONGODB_URI}}
  MONGODB_URI: ${{ secrets.MONGODB_URI }}
  JWT_SECRET: ${{ secrets.JWT_SECRET }}

jobs:
  lint:
    name: Lint 
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup
        uses: actions/setup-node@v3
      - name: Npm install
        run: npm run install:full
      - name: lint
        run: npm run lint

  test:
    name: Test
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup
        uses: actions/setup-node@v3
      - name: Npm install
        run: npm run install:full
      - name: Run tests
        run: npm run test:deployment
        env:
          NODE_ENV: test

  deployment:
    name: Deploy to fly.io
    needs: [lint, test]
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup
        uses: actions/setup-node@v3
      - name: Npm install
        run: npm run install:full
      - name: Build
        run: npm run build
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Deploy to fly.io
        run: flyctl deploy --remote-only

  notify_webhook:
      if: always()
      name: Send discord notification
      needs: [lint, test, deployment]
      runs-on: ubuntu-20.04
      steps:
        - name: Checkout
          uses: actions/checkout@v3
        - name: Success
          if: success()
          uses: rjstone/discord-webhook-notify@v1
          with:
            severity: info
            details: ${{ github.event_name }} succeeded!
            webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
        - name: Failure
          if: failure()
          uses: rjstone/discord-webhook-notify@v1
          with:
            severity: error
            details: ${{ github.event_name }} failed!
            webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}       
        - name: Cancelled
          if: cancelled()
          uses: rjstone/discord-webhook-notify@v1
          with:
            severity: warn
            details: ${{ github.event_name }} canceled!
            webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}  